import type { Metadata } from "next";
import { ContinuumLogoHorizontal, ContinuumMark } from "@/components/brand";
import { Container } from "@/components/layout/container";

export const metadata: Metadata = { title: "Official Brand Preview | Continuum Ventures", description: "Internal approval board for the Continuum Ventures master identity.", robots: { index: false, follow: false } };

export default function BrandPreviewPage() {
  return <div className="bg-[#f3f3ef] text-[#171918]">
    <header className="border-b border-black/10 bg-white py-16 sm:py-24"><Container><p className="text-xs font-bold uppercase tracking-[0.22em] text-emerald-800">Continuum Ventures / Brand Identity v1.0</p><h1 className="mt-5 max-w-4xl text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">The official identity, built for the long term.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-600">Option 3 with Lockup B is the frozen Continuum Ventures identity: one master symbol, one typographic relationship, and one consistent system across every application.</p></Container></header>

    <section className="py-16 sm:py-24"><Container><SectionIntro eyebrow="Official icon" title="The master mark" copy="The selected silhouette is preserved exactly. Symmetric bounds, consistent 12-unit strokes, mitered corner geometry, and round right terminals keep the mark stable from favicon to presentation scale."/><div className="mt-10 grid gap-5 lg:grid-cols-[1fr_1.35fr]"><div className="grid min-h-96 place-items-center rounded-3xl bg-emerald-700 text-white"><ContinuumMark className="size-52"/></div><div className="rounded-3xl border border-black/10 bg-white p-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-stone-500">Small-size proof</p><div className="mt-14 flex flex-wrap items-end gap-10">{[16,24,32,64,128].map(size => <figure key={size} className="flex flex-col items-center gap-4"><ContinuumMark decorative style={{width:size,height:size}}/><figcaption className="font-mono text-[10px] text-stone-400">{size}px</figcaption></figure>)}</div><dl className="mt-14 grid gap-5 border-t border-stone-200 pt-7 text-sm sm:grid-cols-2"><Metric label="Canvas" value="128 × 128"/><Metric label="Stroke" value="12 units"/><Metric label="Outer bounds" value="22–107 / 16–112"/><Metric label="Terminals" value="Round, aligned"/></dl></div></div></Container></section>

    <section className="border-y border-black/10 bg-white py-16 sm:py-24"><Container><SectionIntro eyebrow="Official lockup" title="Premium spacing, finalized" copy="CONTINUUM is set in Manrope 700 and VENTURES in Inter 500. The reduced icon gap and expanded vertical rhythm create a stronger, calmer signature."/><div className="mt-12 grid gap-3 lg:grid-cols-3"><Swatch className="bg-white text-stone-950"><ContinuumLogoHorizontal className="text-[clamp(.62rem,1.4vw,1rem)]"/></Swatch><Swatch className="bg-[#171918] text-white"><ContinuumLogoHorizontal className="text-[clamp(.62rem,1.4vw,1rem)]"/></Swatch><Swatch className="bg-emerald-700 text-white"><ContinuumLogoHorizontal className="text-[clamp(.62rem,1.4vw,1rem)]"/></Swatch></div></Container></section>

    <section className="py-16 sm:py-24"><Container><SectionIntro eyebrow="Applied identity" title="The recommended system in context" copy="Lockup B is used below to test realistic scale, contrast, and hierarchy across everyday brand touchpoints."/><div className="mt-12 grid gap-5 lg:grid-cols-2">
      <Application label="Navbar" className="bg-white"><div className="flex w-full items-center justify-between border-b border-stone-200 px-6 py-5"><ContinuumLogoHorizontal className="text-[14px]"/><span className="rounded-full bg-stone-950 px-4 py-2 text-[10px] font-semibold text-white">Start a Conversation</span></div></Application>
      <Application label="Favicon"><div className="flex items-center gap-7"><div className="grid size-16 place-items-center rounded-2xl bg-white shadow-sm"><ContinuumMark decorative className="size-8 text-emerald-700"/></div><div className="grid size-10 place-items-center rounded-xl bg-stone-950"><ContinuumMark decorative className="size-6 text-white"/></div><ContinuumMark decorative className="size-4 text-emerald-700"/></div></Application>
      <Application label="Footer" className="bg-stone-950 text-white"><div className="w-full"><ContinuumLogoHorizontal className="text-[14px]"/><p className="mt-6 max-w-sm text-xs leading-5 text-stone-400">Building practical businesses, digital platforms, and technology-enabled services.</p><div className="mt-8 border-t border-white/10 pt-4 text-[9px] text-stone-500">© 2026 Continuum Ventures LLC</div></div></Application>
      <Application label="Business card" className="bg-emerald-800 text-white"><div className="flex aspect-[1.75/1] w-full max-w-md flex-col justify-between rounded-sm border border-white/15 p-7 shadow-2xl"><ContinuumMark decorative className="size-10"/><div><ContinuumLogoHorizontal className="text-[10px]"/><p className="mt-4 text-[9px] tracking-wide text-emerald-100">continuumventuresco.com</p></div></div></Application>
      <Application label="Website hero" className="min-h-[28rem] bg-white lg:col-span-2"><div className="grid w-full gap-10 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><ContinuumLogoHorizontal className="text-[10px]"/><p className="mt-12 max-w-2xl text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Building businesses that solve <span className="text-emerald-700">real problems.</span></p><p className="mt-5 max-w-lg text-sm leading-6 text-stone-500">Practical ventures designed to create lasting value.</p></div><ContinuumMark decorative className="mx-auto size-52 text-emerald-700 sm:size-64"/></div></Application>
      <Application label="Presentation title slide" className="min-h-[30rem] bg-[#111513] text-white lg:col-span-2"><div className="flex min-h-[24rem] w-full flex-col justify-between"><ContinuumLogoHorizontal className="text-[11px]"/><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-400">Continuum Ventures</p><p className="mt-4 max-w-3xl text-balance text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">Building for the long term.</p></div><p className="text-xs text-stone-500">Company overview / 2026</p></div></Application>
    </div></Container></section>

    <section className="bg-emerald-800 py-16 text-white sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-emerald-200">Identity status</p><p className="mt-4 text-7xl font-semibold tracking-[-0.06em]">v1.0</p></div><div><h2 className="text-3xl font-semibold tracking-[-0.04em] sm:text-5xl">Approved and frozen</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-emerald-50/85">Option 3 with the finalized premium lockup is the official Continuum Ventures identity. The geometry, proportions, colors, typography, and spacing shown here are now the production standard.</p><div className="mt-10 rounded-2xl bg-white p-8 text-stone-950"><ContinuumLogoHorizontal className="text-[clamp(.7rem,2.2vw,1.4rem)]"/></div></div></div></Container></section>
  </div>;
}

function Swatch({ className, children }: { className: string; children: React.ReactNode }) { return <div className={`grid min-h-52 place-items-center overflow-hidden rounded-2xl border border-black/10 p-6 ${className}`}>{children}</div>; }
function Application({ label, className = "bg-[#e8e8e2]", children }: { label: string; className?: string; children: React.ReactNode }) { return <article className={`relative flex min-h-64 items-center rounded-3xl border border-black/10 p-7 sm:p-10 ${className}`}><span className="absolute right-5 top-5 text-[9px] font-bold uppercase tracking-[0.18em] opacity-45">{label}</span>{children}</article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-stone-400">{label}</dt><dd className="mt-1 font-mono text-stone-800">{value}</dd></div>; }
function SectionIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-800">{eyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">{title}</h2><p className="mt-4 leading-7 text-stone-600">{copy}</p></div>; }
