import type { Metadata } from "next";
import { ContinuumMark } from "@/components/brand";
import { Container } from "@/components/layout/container";

export const metadata: Metadata = { title: "Our Philosophy | Continuum Ventures", description: "How Continuum Ventures approaches building practical businesses with purpose, discipline, and a long-term perspective." };

const principles=[{title:"Clarity",text:"Understand the problem, define the purpose, and make the next decision legible."},{title:"Craftsmanship",text:"Build with care because trust is created through the quality of every detail."},{title:"Continuity",text:"Connect today’s choices to the company we want to be building years from now."},{title:"Curiosity",text:"Stay open, ask better questions, and learn directly from people and markets."},{title:"Ownership",text:"Take responsibility for outcomes and do the work required to improve them."}];
const process=[{number:"01",title:"Observe",text:"Look closely at real behavior, friction, and unmet needs."},{number:"02",title:"Validate",text:"Test the problem, the audience, and the practical path to value."},{number:"03",title:"Build",text:"Create a focused solution with care, speed, and clear priorities."},{number:"04",title:"Grow",text:"Strengthen the business through disciplined learning and execution."}];

export default function PhilosophyPage(){return <>
  <section className="relative isolate overflow-hidden bg-stone-950 py-24 text-white sm:py-32 lg:py-40"><ContinuumMark decorative className="absolute -bottom-32 -right-24 -z-10 size-[34rem] text-stone-900"/><Container><p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-400">Our Philosophy</p><h1 className="mt-7 max-w-5xl text-balance text-5xl font-semibold leading-[1.02] tracking-[-0.06em] sm:text-7xl">Building with purpose.<br/><span className="text-stone-500">Growing for the long term.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-stone-400">Continuum Ventures exists to build businesses that solve meaningful problems through thoughtful execution, disciplined growth, and a commitment to lasting value.</p></Container></section>

  <section className="bg-white py-24 sm:py-32"><Container><div className="grid gap-14 lg:grid-cols-[.72fr_1.28fr] lg:gap-28"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-700">Why we exist</p><h2 className="mt-5 text-balance text-3xl font-semibold tracking-[-0.045em] sm:text-5xl">A company shaped by what it chooses to build—and how.</h2></div><div className="space-y-7 text-lg leading-8 text-stone-600"><p>Continuum Ventures exists because meaningful problems deserve thoughtful businesses built around them. We look for opportunities where practical ideas, disciplined operations, and modern technology can create enduring value.</p><p>We believe growth is most useful when it follows genuine service. That means understanding people clearly, building what improves their experience, and measuring progress by more than momentum alone.</p><p>Our portfolio may span different markets and business models, but every venture shares the same standard: solve something real, execute with care, and build with the future in mind.</p></div></div></Container></section>

  <section className="border-y border-stone-200 bg-[#f5f5f1] py-24 sm:py-32"><Container><div className="grid gap-px overflow-hidden border border-stone-300 bg-stone-300 lg:grid-cols-2"><Statement label="Mission" text="To create businesses, digital platforms, and intelligent services that improve everyday life through practical innovation and disciplined execution."/><Statement label="Vision" text="To build a portfolio of enduring companies recognized for solving meaningful problems with integrity, craftsmanship, and long-term thinking."/></div></Container></section>

  <section className="bg-white py-24 sm:py-32"><Container><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-700">Our principles</p><h2 className="mt-5 max-w-3xl text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">The standards behind every venture.</h2><div className="mt-14 grid border-l border-t border-stone-200 sm:grid-cols-2 lg:grid-cols-5">{principles.map((item,index)=><article key={item.title} className="min-h-72 border-b border-r border-stone-200 p-6"><span className="font-mono text-xs text-emerald-700">0{index+1}</span><h3 className="mt-20 text-lg font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{item.text}</p></article>)}</div></Container></section>

  <section className="bg-stone-950 py-24 text-white sm:py-32"><Container><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Our process</p><h2 className="mt-5 text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">From observation to durable growth.</h2><ol className="mt-16 grid lg:grid-cols-4">{process.map((step,index)=><li key={step.title} className="process-step relative border-l border-white/15 px-6 pb-12 lg:border-l-0 lg:border-t lg:pb-0 lg:pt-8"><span className="absolute -left-1.5 top-0 size-3 rounded-full bg-emerald-500 ring-8 ring-stone-950 lg:-top-1.5 lg:left-6"/><span className="font-mono text-xs text-emerald-400">{step.number}</span><h3 className="mt-12 text-2xl font-semibold">{step.title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-stone-400">{step.text}</p>{index<process.length-1&&<span className="absolute right-3 top-[-.55rem] hidden text-stone-600 lg:block" aria-hidden="true">→</span>}</li>)}</ol></Container></section>

  <section className="bg-emerald-800 py-24 text-white sm:py-32"><Container><div className="max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-200">The continuum</p><h2 className="mt-6 text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">We&apos;re not building a single company.</h2><p className="mt-7 max-w-3xl text-xl leading-9 text-emerald-50/80">We&apos;re building a portfolio of businesses connected by one philosophy:</p><div className="mt-12 grid gap-4 border-t border-white/20 pt-8 text-2xl font-semibold sm:grid-cols-3"><p>Solve real problems.</p><p>Build with intention.</p><p>Create lasting value.</p></div></div></Container></section>
  </>}

function Statement({label,text}:{label:string;text:string}){return <article className="bg-[#f5f5f1] p-8 sm:p-12"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-700">{label}</p><h2 className="mt-10 max-w-xl text-2xl font-semibold leading-9 tracking-[-0.035em] sm:text-3xl">{text}</h2></article>}
